MB-54166 Fix build for 'backup' in CV caused by missing 'cbauth' dependency
couchbase/tools-cv pull request #2
Opened 2022-12-05 15:06 UTC by jamesl33

As part of the work for MB-54166, the `backup` repository switched from a standalone build to one that requires local dependencies (cbauth).

To fix this:
1. The clone stages for `backup` and `tools-common` were separated.
2. `backup` is now clone used `repo` (with the `backup`) group.
3. The separate `CURRENT_PROJECT` and `CB_SERVER_SOURCE_PROJECT` variables have been merged (required as `backup` and `tools-common` must be in a common location to run linting et al.

This ultimately means that `backup` is cloned using `repo` and built with the expected dependencies (`cbauth`) where it wasn't previously. 

Worth noting that this change has the side-effect of cloning `tools-common` into the root of the Couchbase Server install which is fine as it will be ignored and there's no clashing project names.

2022-12-06 14:40 UTC, rdemellow commented
Can you git the PR a better title and add more information to the commit message :)

2022-12-06 14:40 UTC, rdemellow requested changes

2022-12-06 14:40 UTC, rdemellow commented on Jenkinsfile
> +        EXAMINADOR = "${WORKSPACE}/examinador"
Can we separate out concerns in this patch, this is a tidy up rather than a required change. If you want to keep it add a comment in the commit message

2022-12-06 14:40 UTC, rdemellow commented on Jenkinsfile
> +                    return env.GERRIT_PROJECT != 'tools-common';
Maybe add a comment to why != tool-common? Who's the special case?

2022-12-06 14:40 UTC, rdemellow commented on Jenkinsfile
> +                    sh "repo sync --jobs=8"
Please use the PARALLELISM env for the number jobs

2022-12-06 14:40 UTC, rdemellow commented on Jenkinsfile
> +                    sh "repo init -u https://github.com/couchbase/manifest -m ${CB_SERVER_MANIFEST} -g backup"
Could we make use backup as an env so that we can just change that in the future?

2022-12-08 09:33 UTC, jamesl33 commented on Jenkinsfile
> +        EXAMINADOR = "${WORKSPACE}/examinador"
Will revert this change, please let me know if I miss any others.

I'll leave the stuff that removed duplication between backup/tools-common though for now.

2022-12-08 09:38 UTC, jamesl33 commented on Jenkinsfile
> +                    sh "repo sync --jobs=8"
Good catch, didn't know about that :+1:

2022-12-08 09:48 UTC, jamesl33 commented
> Can you git the PR a better title and add more information to the commit message :)

Done :+1:

2022-12-08 11:06 UTC, rdemellow approved these changes

2022-12-08 11:07 UTC, merged